discover:
  iic: "00000367561"
  iic_dc: "00000361589"
  dxs_code: "D6"
  #Indicates the country in which the  acquirer of the charge detail is located per ISO Standard 3166
  aqgeo: "156"
  dRate: "1.00"
  settleCur: "USD"
  env: "CRT"
  generator:
    pre: 5
  exchange: exchange.iso8583
  queue: discover1
  scheduler: true
  sftp:
    host: 192.168.200.236
    port: 10022
    username: "D6"
  zmk:
    component1: C8BF16523D9107949ED5EF29942AF892
    checkValue1: 5DB633
    component2: D6FD4C649804EF2F235E0D5219681073
    checkValue2: BA6911
    component3: 3BCDDA9BD6EAA2ABCE97A783C2FB4608
    checkValue3: A8375D
    zmkCheckValue: 40546B
iso8583:
  message:
    host: 192.168.200.238
    port: 5672
    username: ronhan
    password: Ronhan.2019
    virtualHost: /pacypay/dev
    size: 10
  connection:
    enabled: true
    max: 5
    servers:
      - host: 192.168.200.236
        port: 13344
      - host: 192.168.200.236
        port: 13345
      - host: 192.168.200.230
        port: 13344
      - host: 192.168.200.230
        port: 13345
spring:
  datasource:
    url: jdbc:mysql://192.168.200.111:3306/discoverdevdb?serverTimezone=Asia/Shanghai&useSSL=false
    username: discoverdev
    password: Hg2IDQC=EMiUvlrz
    hikari:
      minimun-idle: 5
      idle-timeout: 60000
      maximum-pool-size: 20
      connection-test-query: select now()
      max-lifetime: 60000
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
  redis:
    database: 10
    host: 192.168.200.225
    port: 6399
    password: goopay

warn:
  receiver: jinzhu.tian@pacypay.com