discover:
  iic: "00000367561"
  iic_dc: "00000361589"
  dxs_code: "D6"
  #Indicates the country in which the  acquirer of the charge detail is located per ISO Standard 3166
  aqgeo: "156"
  dRate: "0"
  settleCur: "USD"
  env: "PRD"
  generator:
    pre: 2
  exchange: exchange.iso8583
  queue: discover1
  scheduler: true
  sftp:
    host: 199.38.157.115
    port: 22
    username: "D6"
  zmk:
    component1: C8BF16523D9107949ED5EF29942AF892
    checkValue1: 5DB633
    component2: D6FD4C649804EF2F235E0D5219681073
    checkValue2: BA6911
    component3: 3BCDDA9BD6EAA2ABCE97A783C2FB4608
    checkValue3: A8375D
    zmkCheckValue: 40546B
iso8583:
  message:
    host: 10.13.4.4
    port: 5672
    username: ENC(ZnmaDRoBCh6EGGgLaCb6eg==)
    password: ENC(4JQ6GhdCM5RoY9V8Smh1t7kzGlzXlFVj)
    virtualHost: /discover
    size: 10
  connection:
    enabled: true
    servers:
      - host: 199.38.157.21
        port: 3344
      - host: 199.38.157.41
        port: 3344
    max: 20
spring:
  datasource:
    url: jdbc:mysql://10.16.0.10:3306/discoverdb?serverTimezone=UTC&useSSL=false
    username: ENC(98G9y9UpSOz9eKljuslssg2JiXDDxJgjzNfuLFUaTx/zysHb+1Yf6Q==)
    password: ENC(4oM/4ws15gXtvwrkT+OQUEs5fLRfeNl/LHRsod6lOl8=)
    hikari:
      minimun-idle: 5
      idle-timeout: 60000
      maximum-pool-size: 20
      connection-test-query: select now()
      max-lifetime: 60000
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
  redis:
    database: 10
    host: 10.13.4.4
    port: 6379
    password: ENC(6w4bsveWEfvJp+vpMcKES6lwQX4qEeb4)

jasypt:
  encryptor:
    password: s8z9Mbo63ly5ckfz

warn:
  receiver: jinzhu.tian@pacypay.com,hao.hong@pacypay.com,zhengming.chen@onerway.com,xiaorong.zhan@onerway.com,jiaren.yan@onerway.com